sdapi_url: "http://example.com/sdapi/v1/txt2img"
matrix:
  debug_room: "!SoMeRoOm:example.com"
  display_name: "imagegen bot"
  homeserver: "https://matrix.org"
  password: "passw0rd"
  username: "@some_user:matrix.org"
