sdapi_url: "http://example.com/sdapi/v1/txt2img"
password: "passw0rd"
username: "@some_user:matrix.org"
homeserver: "https://matrix.org"
display_name: "imagegen bot"
debug_room: "!SoMeRoOm:example.com"