txt2img_api_url: "http://example.com/sdapi/v1/txt2img"
txt2txt_api_url: "http://example.com/run/textgen"
password: "passw0rd"
username: "@some_user:matrix.org"
homeserver: "https://matrix.org"
display_name: "imagegen bot"
debug_room: "!SoMeRoOm:example.com"
txt2txt_history_file: "ai_history.json"