name: Build

on:
  push:

env:
  GO_VERSION: 1.22.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install dependencies
        run: sudo apt-get install libolm-dev libolm3

      - name: Build
        env:
          GO_LDFLAGS: "-s -w -linkmode external -extldflags -static -X main.Tag=$CI_COMMIT_TAG -X main.Commit=$CI_COMMIT_SHA -X 'main.BuildTime=`date '+%b %_d %Y, %H:%M:%S'`'"
        run: go build -v
          
      - name: Test
        run: go test -json > test-${{ env.GO_VERSION }}.json

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ env.GO_VERSION }}
          path: test-${{ env.GO_VERSION }}.json

      - uses: actions/upload-artifact@v3
        with:
          name: bot
          path: bot
          if-no-files-found: error
